config/routes.rb
Rails.application.routes.draw do
  resources :apartments do
    get 'map_location'
  end
  resources :owners

  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  geocoded_by :full_address
  after_validation :geocode
  belongs_to :owner
  validates :owner, presence: true
  def full_address
    address1 + ' ' + address2 + ', '+ city + ', ' + postal_code + ', '+ state + ', ' + country
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :apartments
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    if params[:search].nil?
      @apartments = Apartment.all
    else
      @apartments = Apartment.search(params[:search])
    end

    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end

  end

  def map_location
    @apartment = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.address1
    end
    render json: @hash.to_json
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    @apartments = Apartment.find(params[:id]) #@apartments may also be found using the set_apartment method provided by scaffolding
      @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
        marker.lat apartment.latitude
        marker.lng apartment.longitude
        marker.infowindow apartment.full_address
      end
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
    @owners_for_select = Owner.all.map do |owner|
      [owner.name, owner.id]
    end
    @apartment.owner = Owner.first
  end

  # GET /apartments/1/edit
  def edit
    @owners_for_select = Owner.all.map do |owner|
      [owner.name, owner.id]
    end
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:address1, :address2, :city, :postal_code, :state, :country, :owner_id, :image, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :time, :phone)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment, html: { multipart: true, class: "form-horizontal", role: "form" }) do |f| %>
  <% if @apartment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h4>



      <ul>
      <% @apartment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>



  <div class="form-group">
    <%= f.label :address1, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address1, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postal_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>
  <div class="field">
  <%= select(:apartment, :owner_id, @owners_for_select) %>
  </div>
  <!-- <div class="form-group">
    <%= f.label :owner, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :owner_id, class: "form-control" %>
    </div>
  </div> -->
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @apartment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing apartment</h1>
</div>

<%= render 'form' %>

app/views/apartments/index.html.erb
<div class="page-header">
  <%= link_to new_apartment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Apartment
  <% end %>
  <h1>Listing apartments</h1>
</div>

<form action="/" method="get">
  <input type="text" name="search">
  <input type="submit" value="Search">
</form>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Address1</th>
            <th>Address2</th>
            <th>City</th>
            <th>Postal code</th>
            <th>State</th>
            <th>Country</th>
            <th>Description</th>
              <th>Owner</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @apartments) do |apartment| %>
            <td><%= apartment.address1 %></td>

            <td><%= apartment.address2 %></td>
            <td><%= apartment.city %></td>
            <td><%= apartment.postal_code %></td>
            <td><%= apartment.state %></td>
            <td><%= apartment.country %></td>
            <td><%= apartment.description %></td>
            <td><a href='owners/<%=apartment.owner_id%>'><%= apartment.owner.name %></a></td>
            <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= image_tag apartment.image.url(:thumb) %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div id="allmap">Google map will appear here...</div>



<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'allmap'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(2);
  }
);
</script>

app/views/apartments/new.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New apartment</h1>
</div>

<%= render 'form' %>

app/views/apartments/show.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_apartment_path(@apartment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show apartment</h1>
</div>

<%= image_tag @apartment.image.url(:medium)%>

<dl class="dl-horizontal">
  <dt>Address1:</dt>
  <dd><%= @apartment.address1 %></dd>

  <dt>Address2:</dt>
  <dd><%= @apartment.address2 %></dd>

  <dt>City:</dt>
  <dd><%= @apartment.city %></dd>

  <dt>Postal code:</dt>
  <dd><%= @apartment.postal_code %></dd>

  <dt>State:</dt>
  <dd><%= @apartment.state %></dd>

  <dt>Country:</dt>
  <dd><%= @apartment.country %></dd>

  <dt>Owner:</dt>
  <dd><%= @apartment.owner.name %></dd>

  <dt>Description:</dt>
  <dd><%= @apartment.description %></dd>


</dl>

<!-- <div id="map">Google map will appear here...</div> -->

<div id="map" data-apartment-id="<%=@apartment.id%>">Google Map will appear here...</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'map'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(8);
  }
);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyD5lwNKCcz-pmFGGUNN6KUvkYEl4mNDkEA" type="text/javascript"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"></script>
<script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @owner.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h4>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/owners/edit.html.erb
<div class="page-header">
  <%= link_to owners_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @owner, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing owner</h1>
</div>

<%= render 'form' %>

app/views/owners/index.html.erb
<div class="page-header">
  <%= link_to new_owner_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Owner
  <% end %>
  <h1>Listing owners</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Time</th>
            <th>Phone</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @owners) do |owner| %>
            <td><%= owner.name %></td>
            <td><%= owner.time %></td>
            <td><%= owner.phone %></td>
            <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/owners/new.html.erb
<div class="page-header">
  <%= link_to owners_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New owner</h1>
</div>

<%= render 'form' %>

app/views/owners/show.html.erb
<div class="page-header">
  <%= link_to owners_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_owner_path(@owner), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show owner</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @owner.name %></dd>

  <dt>Time:</dt>
  <dd><%= @owner.time %></dd>

  <dt>Phone:</dt>
  <dd><%= @owner.phone %></dd>

  <p>
  <ul>
    <% @owner.apartments.each do |apartment| %>
        <li>
            <%= apartment.address1 %> <%= apartment.address2 %> <%= apartment.city %> <%= apartment.postal_code %> <%= apartment.state %> <%= apartment.country %>
         </li>
    <% end %>
  </ul>
</p>

</dl>